import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const commodoreFont = localFont({
  src: "./fonts/Bescii-Mono.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${commodoreFont.className} monitor`}>
        <div className={`base-container`}>
          <div className={`base-view`}>
            {children}
          </div>
          <div className={`task-bar`}>
            <div className={`task-bar-item`}>aboutme.txt</div>
            <div className={`task-bar-item`}>Desktop</div>
          </div>
        </div>
        <div className={`base-footer`}>
          <div className={'button-group'}>
            <div className={'green-light'} />
            <div className={'button'}>
              <div className={'button-icon'} />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}

